exports.subjects = {
  10: {
    Maths: [
      'Real Numbers',
      'Polynomials',
      'Pair of Linear Equations in Two Variables',
      'Quadratic Equations',
      'Arithmetic Progressions',
      'Triangles',
      'Coordinate Geometry',
      'Introduction to Trigonometry',
      'Some Applications of Trigonometry',
      'Circles',
      'Constructions',
      'Areas Related to Circle',
      'Surface Areas and Volumes',
      'Statistics',
      'Probability',
    ],
    English: [
      'A Letter To God',
      'Nelson Mandela Long Walk To Freedom',
      'Two Stories About Flying',
      'Diary Of Anne Frank',
      'The Hundred Dresses I',
      'The Hundred Dresses II',
      'Glimpse Of India',
      'Mijbil The Otter',
      'Madam Rides The Bus',
      'The Sermon At Benares',
      'The Proposal',
      'A Triumph of Surgery',
      'The Thief\'s Story',
      'The Midnight Visitor',
      'A Question of Trust',
      'Footprints without Feet',
      'The Making of a Scientist',
      'The Necklace',
      'The Hack Driver',
      'Bholi',
      'The Book That Saved the Earth',
    ],
    Hindi: [
      'पद',
      'राम-लक्ष्मण-परशुराम संवाद',
      'सवैया और कवित्त',
      'आत्मकथ्य',
      'उत्साह और अट नहीं रही',
      'यह दंतुरहित मुस्कान और फसल',
      'छाया मत छूना',
      'कन्यादान',
      'संगतकार',
      'नेताजी का चश्मा',
      'बालगोबिन भगत',
      'लखनवी अंदाज़',
      'मानवीय करुणा की दिव्या चमक',
      'एक कहानी यह भी',
      'स्त्री शिक्षा के विरोधी कुतर्कों का खंडन',
      'नौबतखाने में इबादत',
      'संस्कृति',
      'साखी',
      'पद',
      'दोहे',
      'मनुष्यता',
      'पर्वत प्रदेश में पावस',
      'मधुर-मधुर मेरे दीपक जल',
      'तोप',
      'कर चले हम फ़िदा',
      'आत्मत्राण',
      'बड़े भाई साहब',
      'डायरी का एक पन्ना',
      'तताँरा-वामीरो कथा',
      'तीसरी कसम के शिल्पकार शैलेंद्र',
      'गिरगिट',
      'अब कहाँ दूसरे के दुख से दुखी होने वाले',
      'पतझर में टूटी पत्तियाँ',
      'कारतूस',
    ],
    Science: [
      'Chemical Reactions and Equations',
      'Acids, Bases, and Salts',
      'Metals and Non-Metals',
      'Carbon and Its Compounds',
      'Periodic Classification of Elements',
      'Life Processes',
      'Control and Coordination',
      'How Do Organisms Reproduce',
      'Heredity and Evolution',
      'Light reflection and refraction',
      'Human eye and colorful world',
      'Electricity',
      'Magnetic effect of electric current',
      'Sources of energy',
      'Our Environment',
      'Management of Natural Resources',
    ],
    History: [
      'The Rise of Nationalism in Europe',
      'Nationalism in India',
      'The Making of a Global World',
      'The Age of Industrialisation',
      'Print Culture and the Modern World',
    ],
    Geography: [
      'Resources and Development',
      'Forest and Wildlife Resources',
      'Water Resources',
      'Agriculture ',
      'Minerals and Energy Resources',
      'Manufacturing Industries',
      'Lifelines of National Economy',
    ],
    'Political Science': [
      'Power-sharing',
      'Federalism',
      'Democracy and Diversity',
      'Gender, Religion and Caste',
      'Popular Struggles and Movements',
      'Political Parties',
      'Outcomes of Democracy',
      'Challenges to Democracy',
    ],
    Economics: [
      'Development',
      'Sectors of the Indian Economy',
      'Money and Credit',
      'Globalisation and the Indian Economy',
      'Consumer Rights',
    ],
    Computers: [
      'Internet Basics',
      'Internet Services',
      'Database Concepts',
      'Microsoft Access',
      'HTML',
      'Inserting Images and Links in HTML',
      'Working with Tables in HTML',
      'Introduction to XML',
    ],
  },
  12: {
    Physics: [
      'Electric Charges and Fields',
      'Electrostatic Potential and Capacitance',
      'Current Electricity',
      'Moving Charges and Magnetism',
      'Magnetism and Matter',
      'Electromagnetic Induction',
      'Alternating Current',
      'Electromagnetic Waves',
      'Ray Optics and Optical Instruments',
      'Wave Optics',
      'Dual Nature of Radiation and Matter',
      'Atoms',
      'Nuclei',
      'Semiconductor Electronics',
      'Communication Systems',
    ],
    Chemistry: [
      'The Solid State',
      'Solutions',
      'Electrochemistry',
      'Chemical Kinetics',
      'Surface Chemistry',
      'General Principles and Processes of Isolation of Elements',
      'The p-Block Elements',
      'The d & f Block Elements',
      'Coordination Compounds',
      'Haloalkanes and Haloarenes',
      'Alcohols, Phenols, and Ethers',
      'Aldehydes, Ketones, and Carboxylic Acids',
      'Amines',
      'Biomolecules',
      'Polymers',
      'Chemistry in Everyday Life',
    ],
    Maths: [
      'Relations and Functions',
      'Inverse Trigonometric Functions',
      'Matrices',
      'Determinants',
      'Continuity and Differentiability',
      'Applications of Derivatives',
      'Integrals',
      'Applications of Integrals',
      'Differential Equations',
      'Vector Algebra',
      'Three dimensional Geometry',
      'Linear Programming',
      'Probability',
    ],
    Biology: [
      'Reproduction in Organisms',
      'Sexual Reproduction in Flowering Plants',
      'Human Reproduction',
      'Reproductive Health',
      'Principles of Inheritance and Variation',
      'Molecular Basis of Inheritance',
      'Evolution',
      'Human Health and Diseases',
      'Strategies for Enhancement in Food Production',
      'Microbes in Human Welfare',
      'Biotechnology Principles and Processes',
      'Biotechnology: and its Application',
      'Organisms and Populations',
      'Ecosystem',
      'Biodiversity and Conservation',
      'Environmental Issues',
    ],
    English: [
      'The Last Lesson | Prose',
      'Lost Spring | Prose',
      'Deep Water | Prose',
      'The Rattrap | Prose',
      'Indigo | Prose',
      'Poets and Pancakes | Prose',
      'The Interview | Prose',
      'Going Places | Prose',
      'My Mother at Sixty-six | Poetry',
      'An Elementary School Classroom in a Slum | Poetry',
      'Keeping Quiet | Poetry',
      'A Thing of Beauty | Poetry',
      'The Third Level',
      'The Tiger King',
      'Journey to the end of the Earth',
      'The Enemy',
      'Should Wizard Hit Mommy?',
      'On the Face Of It',
      'Evans Tries an O-Level',
      'Memories of Childhood',
      'A Roadside Stand | Poetry',
      'Aunt Jeniffer\'s Tigers | Poetry',
      'I Sell My Dreams | Short Stories',
      'Eveline | Short Stories',
      'A Wedding in Brownsville | Short Stories',
      'Tomorrow | Short Stories',
      'One Centimetre | Short Stories',
      'A Lecture Upon the Shadow | Poetry',
      'Poems by Milton | Poetry',
      'Poems by Blake | Poetry',
      'Kubla Khan or A Vision in a Dream: A Fragment | Poetry',
      'Trees | Poetry',
      'The Wild Swans at Coole | Poetry',
      'Time and Time Again | Poetry',
      'Blood | Poetry',
      'Freedom | Non Fiction',
      'The Mark on the Wall | Non Fiction',
      'Film-making | Non Fiction',
      'Why the Novel Matters | Non Fiction',
      'The Argumentative Indian | Non Fiction',
      'On Science Fiction | Non Fiction',
      'Chandalika | Drama',
      'Broken Images | Drama',
    ],
    History: [
      'Bricks, Beads and Bones',
      'Colonialism and the Countryside',
      'Through the Eyes of Travellers',
      'Bhakti Sufi Traditions',
      'Kings, Farmers and Towns',
      'Rebels and the Raj',
      'An Imperial Capital: Vijayanagara',
      'Colonial Cities',
      'Kinship, Caste and Class',
      'Mahatma Gandhi and the Nationalist Movement',
      'Peasants, Zamindars and the State',
      'Thinkers, Beliefs and Buildings',
      'Kings and Chronicles',
      'Understanding Partition',
      'Framing the Constitution',
    ],
    'Political Science': [
      'The Cold War Era',
      'The End of Bipolarity',
      'US Hegemony in World Politics',
      'Alternative Centres of Power',
      'Contemporary South Asia',
      'International Organisations',
      'Security in the Contemporary World',
      'Environment and Natural Resources',
      'Globalisation',
      'Challenges of Nation Building',
      'Era of One-Party Dominance',
      'Politics of Planned Development',
      'India’s External Relations',
      'Challenges to And Restoration of The Congress System',
      'The Crisis of Democratic Order',
      'Rise of Popular Movements',
      'Regional Aspirations',
      'Recent Developments in Indian Politics',
    ],
    Geography: [
      'Human Geography Nature and Scope',
      'The World Population Distribution, Density and Growth',
      'Population Composition',
      'Human Development',
      'Primary Activities',
      'Secondary Activities',
      'Tertiary and Quaternary Activities',
      'Transport and Communication',
      'International Trade',
      'Human Settlements',
      'Population - Distribution, Density, Growth and Composition',
      'Migration - Types, Causes and Consequences',
      'Human Development',
      'Human Settlements',
      'Land Resources and Agriculture',
      'Water Resources',
      'Mineral and Energy Resources',
      'Manufacturing Industries',
      'Planning and Sustainable Development in Indian Context',
      'Transport and Communication',
      'International Trade',
      'Geographical Perspective on Selected Issues and Problems',
      'Data - Its Source and Compilation',
      'Data Processing',
      'Graphical Representation of Data',
      'Use of Computer in Data Processing and Mapping',
      'Field Surveys',
      'Spatial Information Technology',
    ],
    Economics: [
      'Introduction',
      'Theory Of Consumer Behaviour',
      'Production and Costs',
      'The Theory Of The Firm Under Perfect Competition',
      'Market Equilibrium',
      'Non-Competitive Markets',
      'National Income Accounting',
      'Money and Banking',
      'Determination Of Income and Employment',
      'Government Budget and The Economy',
      'Open Economy Macroeconomics',
    ],
    'Business Studies': [
      'Nature and Significance of Management',
      'Principles of Management',
      'Business Environment',
      'Planning',
      'Organising',
      'Staffing',
      'Directing',
      'Controlling',
      'Financial Management',
      'Financial Market',
      'Marketing',
      'Consumer Protection',
    ],
    Accountancy: [
      'Accounting for Not-for-profit Organisation',
      'Accounting for Partnership: Basic Concepts',
      'Reconstitution of a Partnership Firm - Admission of a partner',
      'Reconstitution of a Partnership Firm - Retirement /Death of a Partner',
      'Dissolution of Partnership Firm',
      'Accounting for Share Capital',
      'Issue and Redemption of Debentures',
      'Financial Statements of a Company',
      'Analysis of Financial Statements',
      'Accounting Ratios',
      'Cash Flow Statement',
      'Overview of Computerised Accounting System',
      'Spreadsheet',
      'Use of Spreadsheet in Business Applications',
      'Graphs and Charts for Business Data',
      'Data Base Management System for Accounting',
    ],
    'Physical Education': [
      'Planning in Sports',
      'Sports and Nutrition',
      'Yoga and Lifestyle',
      'Physical Education and Sports for CWSN – Children with Special Needs : Divyangs',
      'Children and Sports',
      'Women and Sports',
      'Test and Measurement in Sports',
      'Physiology and Sports',
      'Sports Medicine',
      'Kinesiology, Biomechanics and Sports',
      'Psychology and Sports',
      'Training in Sports',
    ],
    Hindi: [
      'आत्म-परिचय, एक गीत',
      'पतंग',
      'कविता के बहाने, बात सीधी थी पर',
      'कैमरे में बंद अपाहिज',
      'सहर्ष स्वीकारा है',
      'उषा',
      'बादल राग',
      'कवितावली (उत्तर कांड से), लक्ष्मण-मूच्छ और राम का विलाप',
      'रुबाइयाँ, गज़ल',
      'छोटा मेरा खेत, बगुलों के पंख',
      'भक्तिन',
      'बाजार दर्शन',
      'काले मेघा पानी दे',
      'पहलवान की ढोलक',
      'चार्ली चैप्लिन यानी हम सब',
      'नमक',
      'शिरीष के फूल',
      'श्रम-विभाजन और जाति-प्रथा, मेरी कल्पना का आदर्श समाज',
    ],
    'Home Science': [
      'Work, Livelihood and Career',
      'Clinical Nutrition and Dietetics',
      'Public Nutrition and Health',
      'Catering and Food Service Management',
      'Food Processing and Technology',
      'Food Quality and Food Safety',
      'Early Childhood Care and Education',
      'Guidance and Counselling',
      'Special Education and Support Services',
      'Management of Support Services, Institutions and Programmes for Children, Youth and Elderly',
      'Design for Fabric and Apparel',
      'Fashion Design and Merchandising',
      'Production and Quality Control in the Garment Industry',
      'Textile Conservation in Museums',
      'Care and Maintenance of Fabrics in Institutions',
      'Human Resource Management',
      'Hospitality Management',
      'Ergonomics and Designing of Interior and Exterior Spaces',
      'Event Management',
      'Consumer Education and Protection',
      'Development Communication and Journalism',
      'Advocacy',
      'Media Management, Design and Production',
      'Corporate Communication and Public Relations',
      'Management of Development Programme',
    ],
    Sociology: [
      'Introducing Indian Society',
      'The Demographic Structure of the Indian Society',
      'Social Institutions: Continuity and Change',
      'The Market as a Social Institution',
      'Patterns of Social Inequality and Exclusion',
      'The Challenges of Cultural Diversity',
      'Suggestions for Project Work',
      'Structural Change',
      'Cultural Change',
      'The Story of Indian Democracy',
      'Change and Development in Rural Society',
      'Change and Development in Industrial Society',
      'Globalisation and Social Change',
      'Mass Media and Communications',
      'Social Movements',
    ],
    Psychology: [
      'Intelligence And Aptitude',
      'Self And Personality',
      'Human Strengths And Meeting Life Challenges',
      'Psychological Disorders',
      'Therapeutic Approaches And Counselling',
      'Attitude And Social Cognition',
      'Social Influence And Group Processes',
      'Psychology And Life',
      'Developing Psychological Skills',
    ],
    'Computer Science': [
      'Overview of C++',
      'Basic Concepts of OOP and Classes and Objects',
      'Data File Handling',
      'Pointers',
      'Data Structures',
      'Database And SQL',
      'Boolean Algebra',
      'Communication And Computer Networks',
    ],
  },
};
