version: '3'

services:
  app_server:
    networks:
      default:
    command: npm start
    environment:
      - MONGODB_URL=mongodb://mongo1:27017,mongo2:27018,mongo3:27019/enormoDB?retryWrites=true&w=majority
    depends_on:
      - mongo-setup
      - mongo1
      - mongo2
      - mongo3
  
  app_nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 5000:80
    networks:
      default:
    depends_on: 
      - app_server

  mongo-setup:
    container_name: mongo-setup
    image: mongo
    restart: on-failure
    networks:
      default:
    volumes:
      - ./scripts:/scripts
    entrypoint: ['/scripts/setup.sh'] # Make sure this file exists (see below for the setup.sh)
    depends_on:
      - mongo1
      - mongo2
      - mongo3

  mongo1:
    hostname: mongo1
    image: mongo
    expose:
      - 27017
    ports:
      - 27017:27017
    restart: always
    networks:
      default:
    entrypoint:
      [
        '/usr/bin/mongod',
        '--quiet',
        '--logpath',
        '/dev/null',
        '--bind_ip_all',
        '--replSet',
        'rs0',
        '--journal',
        '--dbpath',
        '/data/db',
      ]
    volumes:
      - mongo_data1:/data

  mongo2:
    hostname: mongo2
    image: mongo
    expose:
      - 27017
    ports:
      - 27018:27017
    restart: always
    networks:
      default:
    entrypoint:
      [
        '/usr/bin/mongod',
        '--quiet',
        '--logpath',
        '/dev/null',
        '--bind_ip_all',
        '--replSet',
        'rs0',
        '--journal',
        '--dbpath',
        '/data/db',
      ]
    volumes:
      - mongo_data2:/data

  mongo3:
    hostname: mongo3
    image: mongo
    expose:
      - 27017
    ports:
      - 27019:27017
    restart: always
    networks:
      default:
    entrypoint:
      [
        '/usr/bin/mongod',
        '--quiet',
        '--logpath',
        '/dev/null',
        '--bind_ip_all',
        '--replSet',
        'rs0',
        '--journal',
        '--dbpath',
        '/data/db',
      ]
    volumes:
      - mongo_data3:/data

volumes:
  mongo_data1:
  mongo_data2:
  mongo_data3: