version: '3'
services:
  redis:
    image: 'redis'
    volumes:
      - ./volumes/redis:/data
  text_similarity:
    image: 'dishabhardwaj/textsimilarity_app:latest'
  app_server:
    build: .
    env_file:
      - ./.env
    restart: always
    depends_on:
      - redis
      - text_similarity

volumes:
  redis_data: