version: '3'
services:
  redis:
    image: 'redis'
    volumes:
      - ./volumes/redis:/data
  app_server:
    build: .
    env_file:
      - ./.env
    restart: always
    depends_on:
      - redis

volumes:
  redis_data: