version: '3'
services:
  redis:
    image: 'redis'
    volumes:
      - redis_data:/data
  app_server:
    build: .
    env_file:
      - ./.env
    restart: always
    ports:
      - "12400-12500:8989"
    depends_on:
      - redis

volumes:
  redis_data: