version: '3'
services:
  redis:
    image: 'redis'
    volumes:
      - redis_data:/data
  node-app:
    build: .
    env_file:
      - ./.env
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - redis

volumes:
  redis_data: