version: '3'

services:
  app_server:
    command: npm run dev
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - REDIS_HOST=redis
    extra_hosts:
      - "host.docker.internal:host-gateway"