name: Dev-Deployment

on:
  push: 
    branches: [ develop ]

jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Pull latest code and build
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_DEV_HOST }}
        username: root
        key: ${{ secrets.SSH_SECRET }}
        port: 22
        script: |
          export NVM_DIR=~/.nvm
          source ~/.nvm/nvm.sh
          cd EnormoQB/Backend
          git checkout develop
          git pull
          npm ci
          sudo scripts/updateDockerDev.sh
